### ISSUE TITLE
v2: Question on setConstructorProto()

### ISSUE THREAD

**Issue by klues** [sylvainpolletvillard/ObjectModel#103]
I have a question on v2:
Why is this line needed:
https://github.com/sylvainpolletvillard/ObjectModel/blob/2.x/dist/object-model.js#L126 ?

I use v2 because of IE11 compatibility and this line causes a weird bug in Chrome:
https://bugs.chromium.org/p/chromium/issues/detail?id=919792
and I would be interested to understand this issue a little bit more...

**Comment by sylvainpolletvillard** [comment]
Hi,
This line is required to get a valid `constructor` property for extended models or models derived from an ES6 class. See chapter 2.1 of this article for more details : https://dmitripavlutin.com/understanding-constructor-property/

This performance issue is solved in v3 by using a Proxy trap to specifically return a different value for the "constructor" property. But IE11 does not support Proxies so unfortunately you'll have to stick with v2.

**Comment by sylvainpolletvillard** [comment]
It breaks several tests if this line is removed. If you don't use model extensions, it may be fine, although you could have some surprises if you need to use this constructor property one day.

The perf issue is definitely a bug, probably due to some specific V8 optimizations. Since you are not modifying Array.prototype in your tests, it should not have a perf penalty for any other native arrays. This is up to Chromium team now.

**Comment by klues** [comment]
ok, thanks for the info! I'll re-include the line once the Chrome Bug is fixed (hopefully).
