### ISSUE TITLE
Consider creating ADL serializer to generate ObjectModel?

### ISSUE THREAD

**Issue by shah** [sylvainpolletvillard/ObjectModel#138]
This is a fantastic library, good work @sylvainpolletvillard! If you haven't seen it, check out [ADL](https://github.com/timbod7/adl). If you and that team created an ADL serializer for JavaScript using `ObjectModel` as an underlying infrastructure it would be pretty slick. This way we could have the same algebraic data types on the server as well as the client (in the browser).

**Comment by sylvainpolletvillard** [comment]
I suggest you post this issue on ADL repository since this is more a feature request for ADL rather than for this project. If the ADL team wants to consider a plain JavaScript target with an additional runtime for describing their data models, ObjectModel is not the only available choice, and they will know better than me if this choice makes sense.
