### ISSUE TITLE
Defaults for primitive values and arrays

### ISSUE THREAD

**Issue by vbarbarosh** [sylvainpolletvillard/ObjectModel#27]
I think it will be more consistent if not only object models will have `defaults` but Strings, Numbers, Booleans, and Arrays too. Currently I can't write something like that:
```javascript
var Container = Model.Array([Number, String]);
var a = Container();
```
nor:
```javascript
var Container = Model.Array([Number, String]).defaults([]);
```

**Comment by sylvainpolletvillard** [comment]
Yes I had this idea in mind too. What bothers me is that `objectModel.defaults` and `functionModel.defaults` have a very different meaning and behaviour. This is currently an API flaw in my opinion. A basic model `defaults` method would also be different as it simply checks for undefined argument and return the default value. 

 I would like to remove the `functionModel.defaults` in v3.0 because ES6 default function parameters are more suitable for that purpose. Then I can add a generic `default` method for all models. This method would be different from `objectModel.defaults` which does a deep merge with the prototype.

Do you think it will cause confusion? Any suggestions about naming ?

**Comment by sylvainpolletvillard** [comment]
Looking at your example, the reason Array models do not mimic the Array constructor is that Array constructor has several important flaws in its design:
```
new Array() // [], conflict with JSON resolution
new Array(3) // [undefined, undefined, undefined] ; one argument = length
new Array(3,4) // [3,4] ; two arguments or more = initialization
```

I think the current API for Array models is the good one, and the best solution for this issue is indeed to add a `default` method to all models. Probably for v2.4

**Comment by sylvainpolletvillard** [comment]
Intent to rename `default` method to `defaultTo`. It has the same behaviour than `lodash.defaultTo`. `default` will be used to store the default value.

**Comment by sylvainpolletvillard** [comment]
fixed with the addition of model.defaultTo in v2.4
