### ISSUE TITLE
TypeScript integration

### ISSUE THREAD

**Issue by lbialy** [sylvainpolletvillard/ObjectModel#41]
Hey, I've just found out your project and I find it extremely interesting 👍 Are there any plans for typings for TypeScript? I use it exclusively when I write js code, because I find type checks very helpful for my productivity.

**Comment by sylvainpolletvillard** [comment]
Hi,

I suppose that by "TypeScript integration", you mean add typings to the Model API, not converting existing TypeScript definitions to object models.

This is a strange request since I made ObjectModel to demonstrate the limitations of TypeScript and the benefits of dynamic type checking, While it is possible to use both TypeScript and ObjectModel in the same project as shown on the video demonstration on the website, in practice I doubt that this has any interest.

In the next major version, ObjectModel API will use function models itself to check the correct use of the library. If for any reason you still want static type definitions for this library API, I suggest you to write them yourself and propose them on DefinitelyTypes or flow-typed. But to anwser your question, no there are no plans to add TypeScript on this project. This would be a very odd move since I critize TypeScript from the introduction :smile:

**Comment by equinusocio** [comment]
lol
