### ISSUE TITLE
Ability to generate defaults using a function

### ISSUE THREAD

**Issue by joseandrespg** [sylvainpolletvillard/ObjectModel#42]
Hi!

Would it be possible to have a way to define defaults using a function?

Ex:
```javascript

var FileInfo = Model({
	name: String,
	created: [Date, Number]
}).defaults({
	name: "Untitled file",
	created: Date.now
});

// will execute the function Date.now after a new FileInfo({}) 
// and copy the returned value instead
```

Currently it throws an error because it found a function instead of a Number:
`TypeError: expecting created to be Date or Number, got Function now`

Thanks!

**Comment by sylvainpolletvillard** [comment]
Hi,

`defaults` is a convenient method for setting things in the prototype, so you could write the code this way:

```
var FileInfo = Model({
	name: String,
	created: [Date, Number]
});
FileInfo.prototype.name = "Untitled file";
FileInfo.prototype.created = Date.now()
```

As you can see it is simply a value assignment, so there is no way to tell if you want to assign a reference to the function itself or if you want this function to be invoked to get the value.

Moreover, as the default value is defined in the prototype, **it is shared by all instances** of the model. Definitely not what you want.

So for your usecase, I would suggest to use a factory function to init your models (see "How do I declare a constructor function to be called on instanciation before validating my model ?" here http://objectmodel.js.org/#common-questions)

Another way would be to replace the `created` property by a `getCreationDate` function, so that you can assign `function(){ return Date.now() }` as default for this property.

**Comment by joseandrespg** [comment]
Hi!

The factory solution would be the one that do the job for this case. But at this point would be a big change for us that we might need to agree. And yes, we want to keep the type checking on these fields.

Letting you know our context, we are migrating from mongoose schemas to objectmodel, we have a basic script to automate the definition of the models and avoid duplication, and one of the missing features was this one ("created" dates mainly).

Thanks a lot!

**Comment by sylvainpolletvillard** [comment]
Okay, I may have found another way to do it with a getter/setter:

```
var FileInfo = Model({
	name: String,
	created: [Date, Number]
});
Object.defineProperty(FileInfo.prototype, "created", { 
   get: function(){ return this._created || (this._created = new Date()); },
   set: function(val){ this._created = val; }
})

var f = new FileInfo({ name: "file" });
console.log(f.created); // Fri Feb 03 2017 11:43:28 GMT+0100 (Paris, Madrid)
```

**Comment by rubtk** [comment]
Have a same problem. By using constructor method, have not got how it would work with ArrayModel. Array model dont care about user defined "constructor". I would try go second way.

**Comment by rubtk** [comment]
Nop, this dont work with second method as well. How to solve this problem with ArrayModel's? I think there must be good feature to have some "contructor" feature for ArrayModel.

**Comment by sylvainpolletvillard** [comment]
@rubtk Could you open another issue with some code please ?

**Comment by rubtk** [comment]
@sylvainpolletvillard Solution with prototypes worked finally (there was a bug with debugger breakpoints).
But still, i dont want to use it, coz this looks very creepy for my purposes. I have an invalid input JS object, those must be pre-edited before creating model. Would be nice feature to set somewhere object model constructor for array models, to automatically construct it inside library. Should i open issue for this?

**Comment by sylvainpolletvillard** [comment]
If you need to do a "pre-editing" thing before creating the model instance, I strongly advise you to declare a factory function for that. This is the cleanest approach as everything is explicit, there is no creepy magic involved :

```javascript
MyModel.create = function(...args){
   args = doSomePreEditingThingWith(...args);
   return new MyModel(...args);
}
```

Remember than ArrayModels are supposed to be a transparent layer over regular Arrays, and that regular arrays do not have these custom constructors. Same for object models and regular objects. Only classes have a constructor that could be used for this purpose.

**Comment by rubtk** [comment]
Thanks for help. I understand and agree with you. But problem is i get array of invalid object's, so now "by design" i do foreach of this array **before** creating array model. Does ArrayModel already iterates this source array or not? Or this is real "transparent layer", so technically there are no place to user preprocessing? I declared factory function for single model instance, so you advice is made this for ArrayModel and move proprocessing logic there? Does i understood you right?

**Comment by sylvainpolletvillard** [comment]
You should open another issue with your code so that we can discuss your specific problem.
