### ISSUE TITLE
Predefined assertions

### ISSUE THREAD

**Issue by hiredgun** [sylvainpolletvillard/ObjectModel#49]
Maybe I missed sth but I'm wondering why common assertions like min, max, range etc. or especially assertion checking undeclared properties are not implemented by default by this library?
 Why do I need to write custom assertion in order to check whether some additional properties were provided rather than just setting single option e.g. "additionalProperties: false". When I want to use this lib in several projects I would need to write all assertion again or include them from some dedicated repo to every project. IMHO it's an overkill and if it won't be supported then I will need to find some other lib.

Btw, when I add a custom assertion, for instance: `Model(Number).assert(value => value >= 0 && value <= 100, 'Some msg')` and asserting some deep property, let's say foo.bar.baz, I can't see property path in the error msg. What I get instead is: `TypeError: assertion "'Some msg" returned false for value 2000. For simple expectations like String I get beautiful path: 'expecting foo.bar.baz to be String, got undefined'.

**Comment by sylvainpolletvillard** [comment]
In the first versions of ObjectModel, there were predefined min/max/range assertions in Array models but I don't think it is worth to add by default. There is not much difference between writing `ArrayModel().assert(a => a.length < 10)` and `ArrayModel().max(10)`. 

It is really trivial to add your own assertions helpers through :
```javascript
Model.Array.prototype.min = function(n){ return this.assert(array => array.length >= n) }
Model.Array.prototype.max = function(n){ return this.assert(array => array.length <= n) }
Model.Array.prototype.range = function(min, max){ return this.min(min).max(max) }
```

and voila : `var M = Model.Array(Number).range(2,4)`

The idea is to have a minimalist API that let you declare some generic models that you can reuse accross your projects. For example, I commonly use these : http://objectmodel.js.org/examples/common.js ; I really want to keep this library _small but extensible_, so that other people can work on top of it and make their own models.

**Comment by sylvainpolletvillard** [comment]
Regarding undeclared properties, this is a feature that will come in version 3 (coming very soon). Note that preventing undeclared properties would not be the behaviour by default because it prevents model extension and [Liskov substitution principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle). Also I noticed some libraries and frameworks add private properties to your variables to be able to work with (tested with Vue.js and Angular), so sometimes it is for the best to allow undeclared properties, as long as the rest of the definition is respected.

**Comment by sylvainpolletvillard** [comment]
Regarding the path information in nested models assertion errors, this is definitely something I want to improve but it's tricky to implement. Currently, the easiest way to debug validation errors is to break on exception in your devtools then check the call stack.

**Comment by sylvainpolletvillard** [comment]
I just released v3, which should solve all the problems you mentionned. Let me know if you have other questions
