### ISSUE TITLE
Create React App compatibility issue [v3.1.0]

### ISSUE THREAD

**Issue by filipposarzana** [sylvainpolletvillard/ObjectModel#53]
When adding `objectmodel: ^3.1.0` ad dependency we ran into some issue with CRA integration:

https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

The only thing to do would be keep using `2.x` version of the package?

Thanks

**Comment by sylvainpolletvillard** [comment]
Hi,

ObjectModel 3.x relies on ES6 Proxies, so it can only be used on ES6-compliant browsers, while create-react-app compiles to ES5 and requires every dependency to be ES5 (or already compiled to ES5).

Regarding this part:

> a package you depend on needs compiled or ships code for a non-browser environment. This is considered poor practice in the ecosystem 

This is inaccurate or outdated. All the modern browsers now have >95% ES6 support, so it is acceptable to ship ES6 code if you don't need to support older browsers. Otherwise, you should stick with ObjectModel v2

A reminder of ObjectModel browser support:

```
v1.x
Chrome 29+, Firefox 24+, Edge, Internet Explorer 9+, Opera 20+, Safari 5.1+

v2.x
Support for IE < 11 had to be dropped in v2 because it required many hacks and was holding back other browsers.

v3.x
ObjectModel v3 is built around ES6 Proxies, so requires modern browsers : Edge 14+, Firefox 47+, Chrome 50+, Safari 10+. It also works on Node 6.0+.
```

**Comment by filipposarzana** [comment]
I completely understand the compatibilty matter, but what about keeping the old `2.x` versions updated with all the changes and fixes of the `3.x`

Your package is really really good and since we need support for older browsers we would need one of the two solutions:
- ship ES5 code
- keep updated older versions

Maybe we can make a PR for your, if you like

Thanks!

**Comment by sylvainpolletvillard** [comment]
Unfortunately, it is impossible to get all the changes of v3 while keeping older browser support. As stated before, v3 relies on ES6 Proxies. This feature cannot be transpiled to ES5, there is no suitable polyfill available. See here for more information: https://www.quora.com/Is-there-a-way-to-implement-a-ES6-proxy-under-ES5

I don't take the issue of changing browser support lightly. If I do it, it is because there is no other way possible. 

Now, the v2 docs are still available here : http://objectmodel.js.org/docs/v2/ ; and I will continue to maintain v2. You have most of ObjectModel features with v2, I think you will like it. Give it a try and let me know is you absolutely need some v3 features, I'll see what I can do.

**Comment by filipposarzana** [comment]
@sylvainpolletvillard maybe this can achieve what we want: https://github.com/tvcutsem/harmony-reflect

**Comment by sylvainpolletvillard** [comment]
This one patches the harmony-era (pre-ES6) Proxy object (as implemented in v8 and spidermonkey) to be up-to-date with the ES6 (aka ECMAScript 2015) spec. So it is only useful on some browsers that implement an older version of the Proxy spec, and these browsers need to be started with some developer flags such as `--harmony_proxies`.

It has been proven that Proxy cannot be polyfilled in ES5. Please read the answers in the quora link posted below.
