### ISSUE TITLE
Null-safe object traversal for optional properties

### ISSUE THREAD

**Issue by serhiipalash** [sylvainpolletvillard/ObjectModel#59]
I have model like this

```
const Stars = new ObjectModel({})

const Post = new ObjectModel({
    ...
    stars: [Stars]
})
```

When I check if user starred the post I get error `Undefined is not an object`

```
const post = new Post({})

if (post.stars[userId] === true) {
    console.log('User starred this post')
}
```

Is it possible to use null-safe object traversal for optional properties?

**Comment by sylvainpolletvillard** [comment]
No, null-safe traversal cannot be done on optional properties because the structure is not predictable.

Optional properties are actually a specific case of union type. `[Stars]` is interpreted as `[Stars, null, undefined]`

Now, imagine a union type with two different models that have a different structure:

```
const A = Model({ a: { foo: Number } }), 
      B = Model({ b: { bar: Number } }),
      U = Model({ prop: [A, B] })

const u = U({})
```

Null-safe traversal cannot be used to get `u.prop.a.foo`, because there is a chance `prop` is instance of B and does not have prop `a` declared.

This is the same principle for optional properties. You cannot null-safe traverse the Stars object because there is a chance `stars` is not an instance of Stars, therefore has no access to its declared properties.

**Comment by serhiipalash** [comment]
Great answer! Thanks!

You can close this issue.

Btw, is it possible to specify types for all properties at once?
For example Stars instance could look like this

```
{
   _8dsddf2e23rff_23: true,
   _as839sd3rff_3221: true,
   _kku78rjhhdsd_asd: true,
  ...
}
```

How can I describe in model that any key in Stars should be `true` or `false` and nothing else?

This is separate question. If you want I can create separate issue for it.

**Comment by sylvainpolletvillard** [comment]
If your keys are dynamic, you are probably looking for Map models and not Object Models.
http://objectmodel.js.org/#doc-map-models

```
const Stars = MapModel(String,  Boolean)
```

**Comment by serhiipalash** [comment]
> const Stars = MapModel(String,  Boolean)

Thanks!
