### ISSUE TITLE
Errors are not stacking when using ES6 Classes

### ISSUE THREAD

**Issue by rafaferry** [sylvainpolletvillard/ObjectModel#65]
Hello,

Errors are not stacking when using ES6 Classes.

Here's a test case. 

In the first scenario (without ES6 classes) it works as expected, with two assertion errors being stacked and thrown together. In the second scenario it fails it only one assertion error, from BirthDate, ignoring the Person error.

```
const ObjectModel = require('objectmodel').ObjectModel;
const expect = require('chai').expect;

describe('Assertion Errors Stacking Test', () => {
  it('should throw all errors at the same time', () => {

    ObjectModel.prototype.errorCollector = function collectErrors(errors) {
      const domainErrors = [];
      errors.forEach((error) => {
        domainErrors.push({ bundle: error.message });
      });
      const error = new Error("validationError");
      error.domainErrors = domainErrors;
      throw error;
    };


    const BirthDate = ObjectModel({
      month: Number,
      year: Number,
    }).assert(bd => bd.month > 0 && bd.month <= 12, 'month.invalid');

    const Person = ObjectModel({
      name: String,
      birthDate: BirthDate,
    });

    const json = {
      name: null,
      birthDate: {
        month: 13,
        year: 2017,
      },
    };

    expect(() => {
      const invalidPerson = new Person(json);
    }).to.throw().to.satisfy(error => error.domainErrors.length === 2);
    
  });

  it('should throw all errors at the same time with ES7Classes', () => {

    ObjectModel.prototype.errorCollector = function collectErrors(errors) {
      const domainErrors = [];
      errors.forEach((error) => {
        domainErrors.push({ bundle: error.message });
      });
      const error = new Error("validationError");
      error.domainErrors = domainErrors;
      throw error;
    };


    class BirthDate extends ObjectModel({
      month: Number,
      year: Number,
    }).assert(bd => bd.month > 0 && bd.month <= 12, 'month.invalid') {};

    class Person extends ObjectModel({
      name: String,
      birthDate: BirthDate,
    }) {};

    const json = {
      name: null,
      birthDate: {
        month: 13,
        year: 2017,
      },
    };

    expect(() => {
      const invalidPerson = new Person(json);
    }).to.throw().to.satisfy(error => error.domainErrors.length === 2); //THIS WILL FAIL -> error.domainErrors.length is 1.
    
  });
});
```

**Comment by sylvainpolletvillard** [comment]
Hi again,

Here is what's happening: you set the error collector on `ObjectModel.prototype`, which means this error collector is used on all object models, including BirthDate AND Person

BirthDate is the child model, so its error collector is called first, before Person errorCollector. But in your errorCollector, you are throwing the error at the end ; so there is an uncaught exception that will stop the current execution, and prevent the Person errorCollector to be called next. So what you collected is only the errors of the Birthdate model.

I suggest you to not throw the error if you are using an error collector, so that all the errors are collected in the end.

**Comment by sylvainpolletvillard** [comment]
Regarding why it works for the first case (without class) : 
It may not be documented very well, but the automatic cast to model (_also referred as duck typing in the docs_) only works for models, not classes that extend a model. The reason is that it is ambiguous if we should cast to the class or to the model: 

```js
const BirthDateModel = ObjectModel({
  month: Number,
  year: Number,
}).assert(bd => bd.month > 0 && bd.month <= 12, 'month.invalid')

class BirthDateClass extends BirthDateModel {};

const Person = ObjectModel({
  name: String,
  birthDate: BirthDateClass,
});

const john = new Person({
  name: "John",
  birthDate: {
    month: 11,
    year: 2017,
  },
});

// is john.birthDate a plain object, an instance of BirthDateModel or an instance of BirthDateClass ?
```

Since it is ambiguous, currently there is no automatic casting done, and the object is kept "as it is". So the Birthdate validation error is not catched during the casting phase, but instead during the child model validation phase. That's why the error collectors are called separately.

I think there is room for improvement regarding automatic cast with classes that extend a model, but it is not obvious what is the right thing to do. My recommandation for now would be to **explicitely cast** when using classes:

```js
const john = new Person({
  name: "John",
  birthDate: new BirthDateClass({
    month: 11,
    year: 2017,
  }),
});
```

**Comment by sylvainpolletvillard** [comment]
However I was curious to find out why it was working in the first case (without class). The reason is that the Birthdate validation error was detected in the parent model during the automatic cast phase (aka duck typing) ; so the error was merged with the other one. 

But I found another bug : classes that extend a model are not correctly detected as suitable candidates for automatic cast. This is the actual issue here. If I manage to fix this, you should get the same behaviour.

**Comment by sylvainpolletvillard** [comment]
This should be fixed in v3.4.5. Thanks for the detailed report

**Comment by sylvainpolletvillard** [comment]
Can i close this issue ?

**Comment by sylvainpolletvillard** [comment]
Closed due to inacivity
