### ISSUE TITLE
Private and protected methods and properties

### ISSUE THREAD

**Issue by gotjoshua** [sylvainpolletvillard/ObjectModel#70]
I made an example that employs inheritance and protected and private props and methods:
https://codepen.io/gotjoshua/pen/WyRwbX

I have questions:

1. why can the constructor not set a private var without a set function defined? 
2. what techniques do you recommend for creating protected props and methods?
   (i'm not sure where and how to test if the request is coming from a legit source)

**Comment by sylvainpolletvillard** [comment]
Ah I just answered you on the other issue. Let me copy my response here:

Regarding your question in the pen:
```js
//this._prot="VO"+VO.staticInstanceCount++ //not allowed - but i would expect to be allowed to set my own private var
```

You are not allowed private access here because you are in the extended class constructor, and this function is not part of the model. You can fix it by declaring a setter in the model:
```js
class VO extends ObjectModel({
	VOCLASSNAME : [String],
	_prot       : [String],
	_priv       : [String],
	isValid : FunctionModel().return(Boolean)
}).defaults({
	isValid : function(){ return true; },
	setProt(value){ this._prot = value }
})
{
	constructor(modelDefinition)
	{
		super(modelDefinition)
		this.setProt("VO"+VO.staticInstanceCount++)
		console.log(this.VOCLASSNAME+"(VO) instance number: " + VO.staticInstanceCount++);
	}
```

or by assigning the private property in the model constructor (the super() call):

```js
class VO extends ObjectModel(
	{
		VOCLASSNAME : [String],
		_prot       : [String],
		_priv       : [String],
		isValid : FunctionModel().return(Boolean)
	}).defaults({
		isValid : function(){ return true; }
	})
{
	constructor(modelDefinition)
	{
		super({ ...modelDefinition, _prot: "VO"+VO.staticInstanceCount++ })
		console.log(this.VOCLASSNAME+"(VO) instance number: " + VO.staticInstanceCount++);
	}
```

**Comment by gotjoshua** [comment]
Perfect answer for part 1... Thanks.

What about "protected" methods (that "sibling" members of the same class can access but not others) ?

**Comment by sylvainpolletvillard** [comment]
The private/protected distinction doesn't make much sense in JavaScript since it is a prototype-based language, not a class-based one. One object can have several values for the same property name, if you are looking up in its prototypal chain.

Take this example:
```js
A = Model({ _priv: [String] }).defaults({ 
  _priv: "default", 
  getPriv(){ return this._priv}
})

class B extends A {
  setPriv(x){ this._priv = x }
}

b = new B()
b.setPriv("test");

console.log(b._priv)
console.log(Object.getPrototypeOf(b)._priv)
```

In `setPriv` method, the `_priv` property will be assigned as a property of `b`, not as the model property that will keep its default value "default". So technically you wouldn't assign the private property, but instead declare a new own property of the subclass. The only way to change the model property is to access to the parent model reference with `Object.getPrototypeOf()`, but if you do that, then there is no difference between private/protected.

**Comment by gotjoshua** [comment]
Hmmmpf. Yeah, I found a [stackoverflow answer](https://stackoverflow.com/a/34834120/2919380) that agrees:

> **Protected properties**
> 
> Protected properties, by its nature, requires executing function to know the object of the calling code, to judge whether it should be granted access.
> 
> This is impossible in JS, not because ES6 has no real class, but because caller context is simply unavailable.
> 
> Due to various special natures of JavaScript, for the foreseeable future protected properties shall remain impossible.

**Comment by sylvainpolletvillard** [comment]
Yes, the stackoverflow answer is not totally accurate but I agree on the conclusion

> In ES6 (and before), all private property implementations rely on closure.

Not ObjectModel that rely on Proxies

>  caller context is simply unavailable

I wouldn't say the caller context is unavailable, but the way properties are resolved in JavaScript implies that you change context without noticing, so you lose the real information you are looking for.

**Comment by sylvainpolletvillard** [comment]
Can I close this issue ?
