### ISSUE TITLE
Consider Object.Prop Uniqueness check in SetModels

### ISSUE THREAD

**Issue by gotjoshua** [sylvainpolletvillard/ObjectModel#77]
I am thinking about how to enforce uniqueness in a set and avoid duplicates more strictly.
Specifically i want a SetModel that would cull o2 in this example:
```
let MySetModel = new SetModel(Object);
let o = { prop1:1, prop2:"p2" }
let o2 = { prop1:1, prop2:"p2" }
let o3 = o2
let normalSet = new Set([o,o2,o3]); // Set will not cull o2, but will cull o3
let setModelInstance = new MySetModel(normalSet); // i'd like MySetModel to cull o2
```

There is quite a vibrant [stackexchange](https://stackoverflow.com/questions/201183/how-to-determine-equality-for-two-javascript-objects/16788517#16788517) about the generic topic of object equality. 
And a simple [relevant gist](https://gist.github.com/nicbell/6081098)

How would you propose to enforce this with the current affordances of ObjectModel, and do you think some sort of new (optional) functionality for SetModel could be interesting?

**Comment by sylvainpolletvillard** [comment]
What you are asking would imply that ObjectModel silently mutates the data, but one of the main goals of this library is to be as transparent as possible ; so a SetModel should behave exactly like a regular Set, and it should be possible to remove ObjectModel from the codebase without breaking any logic. That doesn't mean it's always the case, for example you can mutate the data in a custom assertion or in a custom error collector, and achieve what you are trying to do here. But this is not something that is done by the library, it's always code added by the user.

Besides, Object deep comparison is a complex topic, it can be as simple as `JSON.stringify(a) === JSON.stringify(b)` or it can be very hard if you have to deal with circular references, internal properties order, non-enumerable properties, or meta properties (frozen objects, symbols etc.). I used different methods in the past, because it was always a different problem. I don't think there is just one way do to deep object comparison, so I think the best option is to let the user control this behaviour.

Finally, I don't think it would be a good idea to enforce a feature like this, because there are many legitimate usecases where you would have a Set with several objects that are deeply equal; for example, in one of my apps I have a User model with a Set of PhoneNumber, and I initiate a Set of 2 phone numbers with the defaults (same country and empty string for the number).

**Comment by gotjoshua** [comment]
>I don't think it would be a good idea to enforce a feature like this...

Fully agreed, i am thinking more about some sort of optional "deep comparison" - Which method, and how to activate the option, I'm not sure about.

>imply that ObjectModel silently mutates the data

yeah, tricky point. Again, I'd only want it to be an option and I am happy to add to my Model Definition manually - but I am not sure what is the best place/way to do that.

>you can mutate the data in a custom assertion or in a custom error collector

All of the examples for assertion seem to just check the data and  return true or false. Could you offer an example (or 2) that manipulates the data. I am thinking about an assertion that would use Math.floor if the Number is not an integer:
```js
const FlooredInt = BasicModel(Number)
	.assert(function floorIt(n){
		if(!Number.isInteger(n)){
			console.log('flooring');
			console.log(this);
			n = Math.floor(n);
		}
		return true;
	})
console.log(new FlooredInt(1.2));

export class SpaceOM extends
	ObjectModel(
	{
		id: [FlooredInt],
```
but that doesn't seem to work.

Another welcome example would be extending the SetModel to cull non-unique objects based on deep comparison. Perhaps a log message/warning to indicate the mutation is appropriate. Maybe this is a fringe usage of your library, but I'd like to understand deeply enough to be able to implement it when appropriate.

Thanks again for all your time and profound answers!

**Comment by sylvainpolletvillard** [comment]
I noticed that Set models instances do not format properly, I'm working on a fix. Unfortunately, custom devtool formatter is not something that can be unit tested :(

**Comment by gotjoshua** [comment]
Thanks for the formatting efforts!

And big thanks for the example!

**Comment by gotjoshua** [comment]
I feel i am close to getting FlooredInt to work, but not quite:
```js
const FlooredInt = new BasicModel(Number)
	.assert(n => {
		if(!Number.isInteger(n)){
			console.log('flooring: '+ n);
			n = Math.floor(n);
			console.log(n);
		}
		return true;
	})
const FlooredModel = new ObjectModel({id:FlooredInt})
console.log(new FlooredModel({id:1.2}));
```

**Comment by sylvainpolletvillard** [comment]
Primitives like numbers are not mutative. Basic Models don't even involve Proxies, this is just one-time validation. Because if you assign it to something else, you lose the original reference anyway. In other words, it's impossible in JS to assign something to 0 and expect it to be assigned to 1.

However it is possible through the parent ObjectModel, since you mutate the property:
```js
const FlooredInt = new BasicModel(Number)

const FlooredModel = new ObjectModel({id:FlooredInt}).assert(o => {
     for(let key in FlooredModel.definition){
		let n = o[key];
		if(FlooredModel.definition[key] === FlooredInt && key in o && !Number.isInteger(n)){
			console.log('flooring: '+ n);
			n = Math.floor(n);
			console.log(n);
		}
     }
    return true;
})

console.log(new FlooredModel({id:1.2}));
```

**Comment by sylvainpolletvillard** [comment]
_Reminder/Disclaimer: ObjectModel has been intended for data validation, not data mutation. The code examples below divert the indended use of assertions, so I won't provide support for these usecases._

**Comment by gotjoshua** [comment]
Got it. Thanks for humoring me anyway (and for the basic JS tutoring :- /) 

Two small corrections: the [code examples that you mention](https://github.com/sylvainpolletvillard/ObjectModel/issues/77#issuecomment-399284715) are above (not below). Perhaps you want to make a sticky post at the top with that disclaimer.

and (you seem to have already caught the o[key] mutation in your edit)

after ack, i would delete this comment for thread cleanliness (if you don't do it first)

**Comment by sylvainpolletvillard** [comment]
So to sum up : Prop Uniqueness in Set Models can be done with a custom assertion as shown above, but it is not a recommended practice since ObjectModel is not intended to silently mutate data. I think I can close this issue now.
