### ISSUE TITLE
OMap Authority - using ObjectModel in a Meteor - React App

### ISSUE THREAD

**Issue by gotjoshua** [sylvainpolletvillard/ObjectModel#92]
So as you said you ["love to know how everyone uses my work and how can we improve it further"](https://github.com/sylvainpolletvillard/ObjectModel/issues/90#issuecomment-413621597)...

I'd like to ask you for a conceptual review of our data flow model:
[![OMap App Layer Model](https://docs.google.com/drawings/d/e/2PACX-1vTQ0rSDCDAgX8uyGzfMeFPFtt9dE4-PR5x49Hyq6IIdKXQreQiOjZ0ig6U7ZQzUEN3TSMl_3GvIUOZa/pub?w=962&h=1042)](https://docs.google.com/drawings/d/1axUXy8ObBnIZbFfb8GeofHglSKHbX6I_MPesNlkf3tA/edit?usp=sharing)

Basically we tried to take your advice to use ["Models at your API boundaries to validate user input, network responses or serialized data."](https://github.com/sylvainpolletvillard/ObjectModel/issues/72#issuecomment-396567588).

We have data coming from two different sources (so far), one of them with Server Push (Meteor Mongo)  - both sending serialized JSON over the wire. Therefore creating ObjectModels for all our entities and Dynamically Typed Maps feels like a great way to distribute the data down the container/page/component tree.

I'm curious about your thoughts to the diagram and the approach...

**Comment by sylvainpolletvillard** [comment]
I don't have the knowledge to fully understand this diagram, but I think you got it right.

The usecases of ObjectModel I saw previously are:
- server-side validation: on Node.js apps, just before sending API responses or receiving request data. The size and performance overhead is mitigated on the server side
- client-side validation: same but on the client, just before sending requests or after parsing responses JSON.
- form validation: applied over a form data state ; mostly useful when forms have complex relations between values, this is where model assertions come handy. Otherwise, HTML5 validation does the job most of the time.
- local cache invalidation: if you are using IndexedDB or localStorage, and need to do some breaking changes in your state model, validating cached data through an object model is an easy way to detect clients with outdated caches and do some clean up. Other techniques of cache versioning prevent from using old but yet usable data.

**Comment by sylvainpolletvillard** [comment]
I think there may have interesting things to do with Meteor and ObjectModel. I never used Meteor myself so I won't be very helpful, but as I understand it, with Meteor some of the code is shared between server and client, so in theory you can do both server-side and client-side validation. I don't know if this is possible and/or useful.

**Comment by gotjoshua** [comment]
I must say, I am really enjoying to rely on ObjectModel with Meteor.

The shared code is great . We are using shared Object Model definitions for entity types, using instances to populate test data, and casting/validating on the thresholds (JSON exchanges with the CiviAPI and untyped JS objects with the Mongo Collections).

Thanks again for your engagement and for the great library!

**Comment by sylvainpolletvillard** [comment]
Good, then this is a great usecase for this library indeed. I'm glad you figured this out, because dynamic type-checking can be hard to sell.

I have nothing more to say, I think you're already doing a great job. Thanks for sharing your case !
